In [7]:
#taking input of arrays and creating matrix
import numpy as np
rows =int(input())
cols = int(input())
matrix = []
print("Enter elements row by row:")
for i in range(rows):
    row = list(map(int, input().split()))
    matrix.append(row)
A = np.array(matrix)
print("Matrix A:")
print(A)



 3
 3


Enter elements row by row:


 1 2 3
 4 5 6
 7 8 9


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
#matrix Addition
print(A + A)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [9]:
#matrix Subtraction
print(A-A)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
#matrix Multiplication
a=np.dot(A,A)
print(a)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [12]:
#matrix determinant
print(np.linalg.det(A))

0.0


In [13]:
#Matrix Transpose
print(A.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
